name: 📡 Quran Multi Stream Bot

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  stream:
    runs-on: ubuntu-latest
    timeout-minutes: 110

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4

      - name: 🔧 Install ffmpeg
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y ffmpeg

      - name: 🐍 Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: 📦 Install deps
        run: pip install pyTelegramBotAPI==4.18.0

      - name: 🤖 Run bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          STREAM_URL_1: ${{ secrets.STREAM_URL_1 }}
          OUTPUT_URL_1: ${{ secrets.OUTPUT_URL_1 }}
          STREAM_URL_2: ${{ secrets.STREAM_URL_2 }}
          OUTPUT_URL_2: ${{ secrets.OUTPUT_URL_2 }}
        run: python bot.py
